apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: green
  name: green
spec:
  selector:
    matchLabels:
      app: green
  replicas: 1
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - name: green
        image: elevy99927/green:latest
        ports:
        - containerPort: 80